name: Biome

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  biome:
    name: Run Biome scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Biome
        run: npm install @biomejs/biome

      - name: Run Biome
        run: npx @biomejs/biome check .
